In [36]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
import pandas as pd

In [37]:
df=pd.read_csv('data1/ins.csv')

In [38]:
df.head()

age  bought_insurance
0   22                 0
1   25                 0
2   47                 1
3   52                 0
4   46                 1

In [39]:
X=df.iloc[:,:-1].values #locate indexes, all rows, 
Y=df.iloc[:,-1].values

In [40]:
print(X)

[[22]
 [25]
 [47]
 [52]
 [46]
 [56]
 [55]
 [60]
 [62]
 [61]
 [18]
 [28]
 [27]
 [29]
 [49]
 [55]
 [25]
 [58]
 [19]
 [18]
 [21]
 [26]
 [40]
 [45]
 [50]
 [54]
 [23]]


In [41]:
print(Y)

[0 0 1 0 1 1 0 1 1 1 0 0 0 0 1 1 1 1 0 0 0 0 1 1 1 1 0]


In [46]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train, Y_test= train_test_split(X,Y,test_size=2,random_state=1)
print(X_train)
X_train.shape
print(Y_test)



[[19]
 [52]
 [45]
 [18]
 [21]
 [26]
 [46]
 [47]
 [40]
 [55]
 [18]
 [29]
 [60]
 [50]
 [25]
 [25]
 [22]
 [55]
 [23]
 [54]
 [61]
 [62]
 [27]
 [28]
 [56]]
[1 1]


In [47]:
# Create a Logistic Regression Object, perform Logistic Regression
log_reg = LogisticRegression()
log_reg.fit(X_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
# Perform prediction using the test dataset
y_pred = log_reg.predict(X_test)
print(y_pred)

[1 1]


In [49]:
y_pred = log_reg.predict(X_test)
confusion_matrix(Y_test, y_pred)

array([[2]], dtype=int64)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(Y_test, y_pred)

1.0